=pod

=head1 NAME

depinstc - build and verify your ports, in a temporary container

=head1 SYNOPSIS

depinstc [port_dir ...]

=head1 DESCRIPTION

B<depinstc> takes a lists of port directories (or use the current directory), makes a dependency tree, and for each port it will create a temporary container, download and build the port. The built packages are keept (and shared between these containers) in order to avoid redundant builds.

The ports from the command line will have the .footprint and .signature regenerated, and revdep(1), prtverify(1), finddeps(1) and findredundantdeps(1) will be used to check the port.

The pre/post install scripts are disabled when building using the real root as a template container (C<FUNC_ROOT=/>), in order to avoid some rare errors (eg. lilo failing).

It was tested with B<pkgmk> configured with shared directories. If started by the root user (to have write access to F</usr/ports>), it might work with the default settings of B<pkgmk> too.

=head1 EXAMPLES

Build the port from the current directory, with all its dependencies (if not already installed in the real root F</>):

	FUNC_ROOT=/ depinstc

Same as above, but with an explicit directory:

	FUNC_ROOT=/ depinstc /usr/ports/contrib/X

Build the port from the current directory, using the root from B<$FUNC_ROOT> (default to F</var/cache/func-root>, built in advance with C<sudo func create auto configure auto>):

	depinstc

Same as above, but with an explicit directory:

	depinstc my_ports/X

Build all the ports from a repository:

	cd repo && depinstc */

=head1 ENVIRONMENT

=over 4

=item B<SEC_KEY> (default: F<$HOME/.ssh/crux-ports.sec>)

The ports from the command line will be signed with this key (if exists).

=item B<PUB_KEY> (default: F</etc/ports/my.pub>)

The B<SEC_KEY> pair. The regenerated F<.signature> files will have this public key set.

=item B<SHARED_SRC> (default: $PKGMK_SOURCE_DIR)

The host directory holding the sources.

=item B<SHARED_PKG> (default: $PKGMK_PACKAGE_DIR)

The host directory holding the built packages.

=item B<FUNC_ROOT> (default: F</var/cache/func-root>)

The directory used as a template for the temporary container.

=back

See func(1) for the full list of B<FUNC_*> variables.

=head1 COPYRIGHT AND LICENSE

Public domain

=cut
