=pod

=head1 NAME

func-create - create a chroot from CRUX ISO

=head1 SYNOPSIS

func-create [dir]

If B<dir> is missing, F</var/cache/func-root> will be used.

=head1 DESCRIPTION

B<func-create> creates a chroot with all the core packages.

It gets the list of CRUX HTTP mirrors from L<https://crux.nu/Main/Download>, and try them in a random order through HTTPS.

The core packages are mirrored from I<mirror/loop/crux/core/*.pkg.tar.xz> to a temporary directory. When all are downloaded, the packages will be installed with C<pkgadd --root $dir ...>.

=head1 SEE ALSO

func-configure(8), func-chroot(8), func-upgrade(8)

=head1 COPYRIGHT AND LICENSE

Public domain

=cut
