#!/bin/bash

[[ $1 == "" ]] && exit 0

# Use the tool from the current directory, then search the $PATH
# It might make sense to reverse this order to allow customizations.

tool="${BASH_SOURCE%/*}/func-$1"

[[ -x $tool ]] || tool=$(which "func-$1" 2>/dev/null)

export                       \
	FUNC_BIND            \
	FUNC_BIND_RO         \
	FUNC_COW             \
	FUNC_COW_BASE        \
	FUNC_DONT_BIND_CWD   \
	FUNC_PROOT           \
	FUNC_ROOT            \
	FUNC_UNION_ROOT      \

[[ $tool == "" ]] \
	|| shift

prefix="exec"
[[ ${dont_exec:?} ]] && prefix=

$prefix "$tool" "$@"

