#!/bin/bash

[[ -d $FUNC_ROOT ]] || FUNC_ROOT=/var/cache/func-root
(( $UID == 0 ))     || { echo "ERROR: run as root"; exit 1; }

unmount_all() {
	umount "$FUNC_ROOT/dev" "$FUNC_ROOT/tmp" "$FUNC_ROOT/proc" "$FUNC_ROOT/sys"
}

trap unmount_all EXIT
trap "exit 1"    INT QUIT TERM

set -o errexit

mount --bind /dev        "$FUNC_ROOT/dev"
mount --bind /tmp        "$FUNC_ROOT/tmp"
mount --types proc  proc "$FUNC_ROOT/proc"
mount --types sysfs none "$FUNC_ROOT/sys"

chroot "$FUNC_ROOT" "$@"
