=pod

=head1 NAME

func-upgrade - upgrade CRUX chroot

=head1 SYNOPSIS

func-upgrade [dir]

If B<dir> is missing, F</var/cache/func-root> will be used.

=head1 DESCRIPTION

B<func-upgrade> runs C<ports --update>, C<prt-get sysup>, C<revedep> (to find and rebuild broken packages) and C<rejmerge>, in the CRUX chroot created with func-create(8) and func-configure(8).

In adition to this, the chroot is packed as I<<dir>.tar.xz>, in order to be reused (imported by docker or on other compatible systems).

You don't have to have to use this program if the temporary containers built on this chroot share port related files. For example:

=over 4

=item func(1)

uses F</etc/prt-get.conf>, F</etc/ports> and F</usr/ports> from the host

=item depinstc(1)

uses B<$PKGMK_SOURCE_DIR> from the host and keeps B<$PKGMK_PACKAGE_DIR> shared between temporary containers (every package built by a one will be reused by all the others).

=back

=head1 SEE ALSO

func-chroot(8), func-create(8), func-configure(8), func(1), depinstc(1)

=head1 COPYRIGHT AND LICENSE

Public domain

=cut
