#!/bin/bash

if (( UID == 0 )); then
	type=chroot-classic
else
	[[ $FUNC_PROOT != "" ]]                                        \
		|| [[ -e /proc/self/ns/mnt && -e /proc/self/ns/user ]] \
		|| FUNC_PROOT=1

	if [[ $FUNC_PROOT != "" ]]; then
		type=chroot-proot
	else
		type=chroot-namespaces
	fi
fi

set -- $type "$@"

. "${BASH_SOURCE%/*}/func"
