#!/bin/bash

mount_not_needed() {
	[[ $1 =~ ^$PWD && $FUNC_ROOT != / ]]
}

mount_by_type() {
	local type=$1
	local host=$2
	local cont=$3

	case $type in
		none) ;;
		auto)
			[[ -n $host && -n $cont ]] || exit 1
			mount_not_needed "$host" \
				|| FUNC_BIND+=" ${host%/}:${cont%/}"
			;;
		*)
			[[ -n $cont ]] || exit 1
			FUNC_BIND+=" $type:$cont"
	esac
}

show_config() {
(
	. /etc/pkgmk.conf
	printf '%s %s %s\n' "$PKGMK_SOURCE_DIR" "$PKGMK_PACKAGE_DIR" "$PKGMK_WORK_DIR"
)
}

main() {
	(( $# < 2 )) && exit 1

	local typeSRC=$1
	local typePKG=$2
	shift 2

	local hostSRC hostPKG hostWORK
	read -r hostSRC hostPKG hostWORK < <( show_config )

	local contSRC contPKG contWORK
	read -r contSRC contPKG contWORK < <(
		"${BASH_SOURCE%/*}/func" chroot bash < <(
			sed 's/^main "$@"$/show_config/' \
				< "${BASH_SOURCE[0]}"
		)
	)

	# avoid union
	mount_by_type auto       "$hostWORK" "$contWORK"

	mount_by_type "$typeSRC" "$hostSRC"  "$contSRC"
	mount_by_type "$typePKG" "$hostPKG"  "$contPKG"

	. "${BASH_SOURCE%/*}/func"
}

main "$@"
