=pod

=head1 NAME

portc - execute port command in a temporary container

=head1 SYNOPSIS

portc [cmd args]

=head1 DESCRIPTION

B<portc> runs C<func> with additional mounts. It's intended to help running build commands in a clean container (eg. find the proper dependencies).

The C<func> program is already mounting F</etc/ports> and F</usr/ports> inside the continer. The C<portc> adds more mounts:

=over 4

=item B<PKGMK_SOURCE_DIR> - to reuse the source

=item B<PKGMK_PACKAGE_DIR> - to reuse the builds

=item B<PKGMK_WORK_DIR> - speed-up by avoiding COW from unionfs-fuse(1)

=item B<CCACHE_DIR>

=item F<$HOME/.cache/pp>

=back

=head1 ENVIRONMENT

=over 4

=item B<FUNC_ROOT> (default: F</var/cache/func-root>)

The container template.

=back

=head1 SEE ALSO

func(1)

=head1 COPYRIGHT AND LICENSE

Public domain

=cut
