#!/bin/bash

run_me_in_container() {
	export FUNC_DONT_BIND_CWD=not_needed
	exec ${BASH_SOURCE%/*}/func      \
		clone        /    auto   \
		pkgmk        auto auto   \
		ccache                   \
		oprt                     \
		prt-get                  \
		chroot                   \
		bash < <(
			sed 's/^run_me_in_container$/run_me/' \
				< $BASH_SOURCE
		)
}

run_me() {
	if have_oprt; then
		sysupc_with_oprt
	else
		sysupc_with_prt_get
	fi
}

have_oprt() {
	oprt=$(which oprt)

	[[ -x $oprt ]]
}

sysupc_with_oprt() {
	export OPRT_BUILD_WITH_FAKEROOT=needed_by_some_ports
	export OPRT_INSTALL_WITH_FORCE=do_not_care
	export OPRT_SKIP_REJMERGE=do_not_care_rejmerge
	export OPRT_DONT_LOG=do_not_pollute_the_log_if_mounted
	export OPRT_DONT_RUN_SCRIPTS=lilo_fails_installing_kernel
	export OPRT_DONT_ASK_SCRIPT=we_dont_run_scripts

	# avoid rebuilding some big packages
	[[ ${REVDEP_OPTS+defines} ]] \
		&& export OPRT_REVDEP=$REVDEP_OPTS

	set -o xtrace
	oprt-update
}

sysupc_with_prt_get() {
	# lilo fails installing linux-stable
	ed -s /etc/prt-get.conf <<-EOF
		g/runscripts/d
		w
	EOF

	set -o xtrace
	prt-get sysup || exit 1

	[[ ${REVDEP_OPTS+defined} ]] \
		|| REVDEP_OPTS="-i libreoffice"
	REVDEP_OPTS="${REVDEP_OPTS//[^a-zA-Z0-9 -]/}"

	revdep $REVDEP_OPTS | xargs --no-run-if-empty prt-get update -fr
}

run_me_in_container
